/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Other.LocalDataStorage;
import Other.SaveToDb;
import Persistent.Student;
import Persistent.Subject;
import Persistent.Task;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author adam
 */
public class TaskFrame extends javax.swing.JFrame {
    
    private DefaultComboBoxModel<String> studentsModel;
    private DefaultComboBoxModel<String> subjectsModel;
    private final TasksPaneModel tasksPaneModel;
    private Task task;
    private String errorMsg;
    private boolean newTask;
    private String studentComboInput;
    private String subjectComboInput;
    

    /**
     * Creates new form TaskFrame
     */
    public TaskFrame(TasksPaneModel tasksPaneModel) {
        this.tasksPaneModel = tasksPaneModel;
        getStudentsModel();
        getSubjectsModel();
        initComponents();
        setTitle("Nový úkol");
        newTask = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        saveTask = new javax.swing.JButton();
        cancelTask = new javax.swing.JButton();
        headline1 = new javax.swing.JLabel();
        studentComboBox = new javax.swing.JComboBox();
        studentComboLabel = new javax.swing.JLabel();
        subjectComboBox = new javax.swing.JComboBox();
        subjectComboLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setText("Název");

        descriptionLabel.setText("Popis");

        saveTask.setText("Uložit");
        saveTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTask(evt);
            }
        });

        cancelTask.setText("Zrušit");
        cancelTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTask(evt);
            }
        });

        headline1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        headline1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headline1.setText("Nový úkol");

        studentComboBox.setModel(studentsModel);

        studentComboLabel.setText("Student");

        subjectComboBox.setModel(subjectsModel);

        subjectComboLabel.setText("Předmět");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(saveTask)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelTask)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subjectComboLabel)
                                    .addComponent(studentComboLabel)
                                    .addComponent(descriptionLabel)
                                    .addComponent(nameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(subjectComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(description, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(name)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(headline1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headline1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descriptionLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentComboLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectComboLabel))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveTask)
                    .addComponent(cancelTask))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveTask(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTask
        if(checkInputData()) {
            if(newTask) {
                String firstSplit[] =  studentComboInput.split("\\(");
                String secondSplit[] = firstSplit[1].split("\\)"); 
                Student student =  LocalDataStorage.getTaskUsingXname(secondSplit[0]).getStudent();
                Subject subject = LocalDataStorage.getTaskUsingSubject(subjectComboInput.toString()).getSubject();
                task = new Task(name.getText(), description.getText(), subject, student);
                if(LocalDataStorage.addTask(task)) {
                    tasksPaneModel.fireTableDataChanged();
                    name.setText("");
                    description.setText("");
                    new Thread(new SaveToDb(task)).start();
                    cancelTask(evt);
                }
                else {
                    
                }
            }
            else {
                
            }
        }
        else {
            JOptionPane.showMessageDialog(this, errorMsg, "Chyba", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveTask

    private void cancelTask(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelTask
        this.dispose();
    }//GEN-LAST:event_cancelTask

    private DefaultComboBoxModel getStudentsModel() {
        studentsModel = new DefaultComboBoxModel<String>();
        studentsModel.addElement("");
        for(Student student : LocalDataStorage.studentsList) {
            studentsModel.addElement(student.toString() + " (" + student.getXname() + ")");
        }
        return studentsModel;
    }
    
    private DefaultComboBoxModel getSubjectsModel() {
        subjectsModel = new DefaultComboBoxModel<String>();
        subjectsModel.addElement("");
        for(Subject subject : LocalDataStorage.subjectsList) {
            subjectsModel.addElement(subject.toString());
        }
        return subjectsModel;
    }
    
    private boolean checkInputData() {
        String nameInput = name.getText();
        String descriptionInput = description.getText();
        studentComboInput = studentsModel.getSelectedItem().toString();
        subjectComboInput = subjectsModel.getSelectedItem().toString();
        
        if(nameInput.isEmpty()) {
            errorMsg = "Úkol musí mít název";
            return false;
        }
        else if(descriptionInput.isEmpty()) {
            errorMsg = "Každý úkol musí mít svůj popis";
            return false;
        }
        else if(studentComboInput.isEmpty()) {
            errorMsg = "Každý úkol musí mít přiřazeného studenta, který ho vypracuje";
            return false;
        }
        else if(subjectComboInput.isEmpty()) {
            errorMsg = "Každý úkol musí mít přiřazený předmět, které se ho týká";
            return false;
        }
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelTask;
    private javax.swing.JTextField description;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel headline1;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton saveTask;
    private javax.swing.JComboBox studentComboBox;
    private javax.swing.JLabel studentComboLabel;
    private javax.swing.JComboBox subjectComboBox;
    private javax.swing.JLabel subjectComboLabel;
    // End of variables declaration//GEN-END:variables
}
